
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import AuthRedirect from "@/component/authRedirect";
import useSessionHandler from "./hooks/useSessionHandler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
		<Provider>


    <html lang="en">
      <body className="min-w-screen min-h-screen bg-blue-50">
				<AuthRedirect/>
				{children}</body>
    </html>
		</Provider>

  );
}
